apiVersion: v1
kind: Service
metadata:
  name: service-two
  labels:
    app: service-two
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: service-two